version: '2'
services:
  web:
    build:
      context: ./docker
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    links:
      - app
    restart: always

  mysql:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=spaidb
      - MYSQL_USER=spai
      - MYSQL_PASSWORD=secret
    restart: always

  app:
    build:
      context: ./docker
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    restart: always

volumes:
  mysql-data:
    driver: local
